[package]
name = "config-share"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
sha = "1.0.3"
rayon = "1.7.0"
log = "0.4.17"
